### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [arangodb/docs#1030]
Hi!

We are investigating different databases for our solution. And ArangoDB is one of the candidates. And one of the requirements is support of different architectures (at least x86-64 and ARM).

I have checked the documentation but did not find any word about supported architectures - only about supported operating systems.

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know).

This kind of information is important for the end-users.

Thanks in advance!

**Comment by Simran-B** [comment]
The supported architecture is x86-64. ARM support is under way. The instruction set requirements are listed on the download pages, e.g.
https://www.arangodb.com/download-major/ubuntu/
3.9.x requires SSE 4.2 and AVX (3.8.x and older don't require AVX). There are 3.9 Docker images without AVX for Rosetta 2 emulation on Apple silicon, but they are not verified for production use.

I'll discuss with the engineering and documentation teams where this information should be placed.
