### ISSUE TITLE
[Guide Not Working] :: Create an ArangoDB cluster on Microsoft Azure

### ISSUE THREAD

**Issue by bobaikato** [arangodb/docs#1072]
I am interested in using this guide. But unfortunately, I am unable to get it to work. See the error below
I am using Mac.

**unable to load Private Key**
```

4416181932:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/libressl/libressl-2.8/crypto/pem/pem_lib.c:684:Expecting: ANY PRIVATE KEY
Failed to create SSH-Key. Exiting.
```

**Comment by Simran-B** [comment]
Hi @B0BAI, since the cloud deployment tutorials no longer work, we decided to remove them. Given all the other work we have and because this is mostly about third-party services, we don't plan on adding new deployment tutorials and rather focus on first-party content.
