### ISSUE TITLE
Remove references to Mesos deployments

### ISSUE THREAD

**Issue by jsteemann** [arangodb/docs#109]
In devel, references to Mesos setups have been removed from README_maintainers.md recently. 
Our documentation still mentions Mesos setups, and I am not sure if we still want to encourage such deployments. I guess the answer is no.

**Comment by Simran-B** [comment]
PR: https://github.com/arangodb/docs/pull/110

**Comment by Simran-B** [comment]
Merged & published.

**Comment by Simran-B** [comment]
3.3 and 3.4: #241 
2.8..3.2 to be removed.
