### ISSUE TITLE
typo: forceForceHint

### ISSUE THREAD

**Issue by ArtskydJ** [arangodb/docs#1123]
I believe there is a typo in `operations-for.md`.  Perhaps it's supposed to be `forceIndexHint`?

https://cs.github.com/?scopeName=All+repos&scope=&q=forceForceHint+owner%3Aarangodb

I'd created a PR #1120 that changed one instance, but more than just the 3.10 docs have the typo.

**Comment by Simran-B** [comment]
Thanks for noting and reporting this typo. Fixed by the following commit for all currently supported versions: https://github.com/arangodb/docs/commit/0aa56ec33ebe778acfa5bab25f475ce423d2bba6
