### ISSUE TITLE
ArangoDeployment spec.architecture missing from docs

### ISSUE THREAD

**Issue by ddelange** [arangodb/docs#1141]
Hi! 👋 

The [documentation](https://www.arangodb.com/docs/3.10/deployment-kubernetes-deployment-resource.html) for `ArangoDeployment` is missing an entry for `spec.architecture` which is a [list[str]](https://github.com/arangodb/kube-arangodb/blob/1.2.19/pkg/apis/deployment/v2alpha1/architecture.go#L42) introduced in https://github.com/arangodb/kube-arangodb/pull/900 and [needed](https://github.com/arangodb/arangodb-docker/issues/53#issuecomment-1249332385) to run 3.10 on ARM64 processors.

**Comment by ddelange** [comment]
fwiw in the original implementation there was an error [`"Only one architecture type is supported currently"`](https://github.com/arangodb/kube-arangodb/pull/900/files#diff-d463af5ab5278e628363922296b9d4634c8088448fe08d2034493d337855d458R43), but that [seems to have disappeared](https://github.com/arangodb/kube-arangodb/blame/1.2.19/pkg/apis/deployment/v2alpha1/architecture.go#L42) before/during/after merging that PR.

only the first architecture specified here is respected, however. the rest is ignored (only one nodeAffinity is added to the pods). maybe the error should not have gone 🤔 ref https://github.com/arangodb/arangodb-docker/issues/110#issuecomment-1273629942

**Comment by ddelange** [comment]
fwiw, `<group>.id` is also missing from docs ref https://github.com/arangodb/kube-arangodb/issues/1141#issuecomment-1274286483

**Comment by ddelange** [comment]
@nerpaula @Simran-B I think this should be re-opened:

as far as I can see, the linked PR documents the arango operator's `spec.architectures` field, not the `ArangoDeployment` resource's `spec.architecture` field.

the operator supports multiple architectures passed as list[str], whereas the ArangoDeployment field is list[str] but only supports one architecture in that list, see previous comments above.

**Comment by Simran-B** [comment]
@ddelange Thanks for pointing out that something isn't right with the new content. I clarified with @jwierzbo that the deployment specification uses `spec.architecture` (singular) for defining an architecture, and it should normally be a list with a single item only. However, for the purpose of migrating to a different architecture, you can specify two architectures, and the first one defines the architecture you want to migrate to. After the migration, the old architecture should be removed from the list. It's being discussed internally whether a secondary architecture should be supported as a fallback, i.e. having two architectures in the deployment specification permanently.

Clarifications PR: https://github.com/arangodb/docs/pull/1187

**Comment by ddelange** [comment]
awesome thanks so much for the quick action and the clear explanation!

**Comment by ddelange** [comment]
@Simran-B `spec.architecture` seems still missing in the ArangoDeployment resource [docs](https://www.arangodb.com/docs/3.11/deployment-kubernetes-deployment-resource.html), is this part not auto-generated? also related to #1188

**Comment by Simran-B** [comment]
#1187 is not merged yet, and we typically re-publish the docs for a release (v3.9.5 is imminent).
