### ISSUE TITLE
Update Swagger file in main repo (automatically?)

### ISSUE THREAD

**Issue by Simran-B** [arangodb/docs#124]
Backport to 3.5 / 3.4?
https://github.com/arangodb/arangodb/pull/9045

Does the Swagger file get re-generated and committed in the main repo on every release?
https://github.com/arangodb/arangodb/commits/3.5/js/apps/system/_admin/aardvark/APP/api-docs.json

Do we need to manually update it / can we automate this?

**Comment by dothebart** [comment]
#9045 should be backported.

**Comment by Simran-B** [comment]
arangodb/arangodb#9602
arangodb/arangodb#9603

The Swagger file was definitely missing the minReplicationFactor changes, which was added in v3.5.0-rc.5 (2019-07-22):

```diff
@@ -726,6 +751,11 @@
                 "keyOptions": {
                     "$ref": "#/definitions/key_generator_type"
                 },
+                "minReplicationFactor": {
+                    "description": "contains how many minimal copies of each shard need to be in sync on different DBServers.\nThe shards will refuse to write, if we have less then these many copies in sync. *Cluster specific attribute.*\n\n",
+                    "format": "",
+                    "type": "integer"
+                },
                 "name": {
                     "description": "literal name of this collection\n\n",
                     "type": "string"
```

So I guess sometimes it was updated manually but this time it was not and there is no automatic process to do it.

**Comment by Simran-B** [comment]
Jenkins job `arangodb-ANY-examples` can be used to re-generate examples + Swagger in the docs repo, then the Swagger JSON file can be picked and copied over to the main repo where it is used by the Web UI (for Swagger UI).
