### ISSUE TITLE
"insert into" not working any more ? ("insert in" is ok)

### ISSUE THREAD

**Issue by Karl01** [arangodb/docs#128]
Debian stable, arangod 3.4.7 at least on my setup "INTO" is nor working a described in "docs/3.4/aql/operations-insert.md", "IN" writes fine to db

**Comment by Simran-B** [comment]
I can't see a problem in v3.4.7 on Windows. Explaining the query shows an execution plan with `IN` in both cases:

```js
Query String:
 INSERT {foo:1} INTO test

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET #1 = { "foo" : 1 }   /* json expression */   /* const assignment */
  3   InsertNode           0     - INSERT #1 IN test 
```

Can you post your full query and describe the exact problem you encounter please?

**Comment by Simran-B** [comment]
Closing because not reproducible and lack of feedback.
