### ISSUE TITLE
Storage engine differences

### ISSUE THREAD

**Issue by Simran-B** [arangodb/docs#140]
There are some remarks here and there which do not distinguish between MMFiles and RocksDB, e.g.

```
`collection.figures()`

Returns an object containing statistics about the collection.

{% hint 'info' %}
Retrieving the figures will always load the collection into memory.
{% endhint %}
```

Does RocksDB load the collection metadata only, and does it so on first use or is it always in memory?

**Comment by Simran-B** [comment]
Related:

```
`collection.load()`

Loads a collection into memory.

{% hint 'info' %}
Cluster collections are loaded at all times.
{% endhint %}
```

#84 #35

**Comment by dothebart** [comment]
'Loading collections' in MMFiles includes building up indices in RAM, which may take time depending on the collection size and the index complexity. 
For rocksdb we don't do this.
