### ISSUE TITLE
AQL: Multi-line comments must be terminated from 3.6.0 on

### ISSUE THREAD

**Issue by Simran-B** [arangodb/docs#185]
The following is not allowed in current devel anymore:

```
RETURN 1
/*
RETURN 2
```

There must not be an unterminated multi-line comment:

```
RETURN 1
/*
RETURN 2
*/
```

Counts don't have to match, as anything between `/*` and `*/` is considered as comment body, including additional `/*`.

Prism.js needs to be updated as well!

**Comment by jsteemann** [comment]
Note that this is not only 3.6 and onwards.
The "fix" has also been backported to 3.4 and 3.5 IIRC.

**Comment by Simran-B** [comment]
Prism.js PR opened: https://github.com/PrismJS/prism/pull/2089

It is no longer allowed to have unterminated multi-line comments in AQL (as a side-effect of a bug-fix to prevent unterminated strings) from these versions on:

- 3.4.9 https://github.com/arangodb/arangodb/pull/10157
- 3.5.1 https://github.com/arangodb/arangodb/pull/10156
- 3.6.0 https://github.com/arangodb/arangodb/pull/10155

**Comment by Simran-B** [comment]
Nothing says that it was supported to have unterminated multi-line comments, so nothing to change in the docs IMO:
https://www.arangodb.com/docs/stable/aql/fundamentals-syntax.html#comments
