### ISSUE TITLE
Foxx + VST = request module not working?

### ISSUE THREAD

**Issue by Simran-B** [arangodb/docs#211]
> [this PR](https://github.com/arangodb/arangodb/pull/10349#discussion_r341887352) will fix it. However, using `const request = require("@arangodb/request");` from arangosh which doesn't use fuerte is the primary thing which needs discussion. Encouraging using it in the documentation isn't that clever. I'd change that at least as of 3.6.

**Comment by dothebart** [comment]
The request module uses the simple http client. If you write tests in arangosh to work with your foxx service, thats not that smart to that regard. 
In the end we either want to get rid of it, or fix it - aka use fuerte with it under the hood.

**Comment by Simran-B** [comment]
Sounds like it should be fixed / use fuerte. As a user I don't care about the details, I simply want to be able to make requests, and using the request module for that is the obvious way.

We might want to add a known issue entry to the docs that it's broken in certain versions when using VST,

**Comment by pluma** [comment]
> If you write tests in arangosh to work with your foxx service, thats not that smart to that regard.

We advise users to write integration tests for Foxx by using the request module to talk to the service. So a service might have a test file that makes a request to the same service, no arangosh needed.

The best approach would be to intercept requests to the same server and use fuerte so users don't have to think about this.

An interesting improvement on top of this would be to add VST support to the request module (via the protocol in URLs) to allow services to talk to external things via VST too (e.g. other ArangoDB servers or third-party services that implement VST).
