### ISSUE TITLE
Couldn't read example 

### ISSUE THREAD

**Issue by zzice** [arangodb/docs#266]
After executing `bundle exec jekyll serve`，info：
`Couldn't read example at /home/user1/docs/3.5//generated/Examples/dbProperties.generated, required by 3.5/data-modeling-databases-working-with.md

Couldn't read example at /home/user1/docs/3.6//generated/Examples/dbProperties_cluster.generated, required by 3.6/data-modeling-databases-working-with.md`

**Comment by Simran-B** [comment]
This is expected in the devel version (currently the 3.6 folder) until we re-generate the examples manually (sporadically, at least once shortly before a release).

I need to check what it wrong with 3.5 however. It should not stop jekyll from building the docs anyway, and everything should work normally except that the reported example execution result will be missing.

**Comment by Simran-B** [comment]
Ah, I [added an example](https://github.com/arangodb/docs/pull/243/files#diff-abbf3bcf02fba154cced79929d2814d5) recently and did not update the generated files.
https://github.com/arangodb/docs/commit/d692d11175fcaef935f7748b415b3460da7bb8e7#diff-efff5702c68ca50be870b7a8e85d4656 added it for 3.6.

It's now in master for 3.5: https://github.com/arangodb/docs/commit/909088ffb6715d2bf6047557e357173cfca19cc4

**Comment by konsultaner** [comment]
@Simran-B can only you update the examples? Or is it possible for contributors?

**Comment by Simran-B** [comment]
We have an internal Jenkins job and process for that @konsultaner

**Comment by konsultaner** [comment]
Ah ok, can you also run PRs to test for validity?

**Comment by Simran-B** [comment]
We do run it against feature branches that require it, check the Netlify previews, and merge the PRs including the generated examples. Additionally, we generate the examples for releases, also via a branch.

**Comment by konsultaner** [comment]
@Simran-B I ran the netlify.sh, but it didn't generate anything 😕 I added a PR-draft, if you have a minute maybe you can help me with it.

https://github.com/arangodb/docs/pull/1290
