### ISSUE TITLE
How do you version control ArangoDB schema?

### ISSUE THREAD

**Issue by bionicles** [arangodb/docs#312]
I want to put a script in my version control system which makes a graph with edge definitions. The docs for how to do this seem spread over a few different areas of the docs site; could we please consolidate graph collection CRUD and clarify for this use case?

How do you write a script to make a graph, add vertex collections, add edge collections and edge definitions?

How do you run that script on your DB?

This would help us automatically recover from problems because we could easily recover the database settings (and track changes in version control). Doing stuff through the console isn’t as reproducible as using a script

**Comment by dothebart** [comment]
Hi, do you mean something along the lines of https://github.com/deusdat/arangomigo ?

**Comment by bionicles** [comment]
Ideally the solution would be more like https://github.com/skeema/skeema

In Skeema, you write down the schema you want, and it figures out how to make the database match the schema

In Arangomigo, you write YAML for every step of the process to change the DB. That's a LOT more work because you have to explicitly write each change in some machine language and depend on some random dude's 3rd-party software to translate that into Arango commands. 

I'd rather just write an Arango.JS script to make what I want. If I change that, then it's arango's job to figure out how to change to match the new schema. But I guess ArangoDB doesn't support declarative schemas, only imperative migrations?

**Comment by bionicles** [comment]
simpler improvement: to make docs easier to CTRL-F find stuff as a developer, can we put the docs on fewer pages? I feel like i have to have a bunch of tabs open and guess which one has what I'm looking for:

https://www.arangodb.com/docs/stable/drivers/js-reference-graph.html
https://www.arangodb.com/docs/stable/drivers/js-reference-graph-vertices.html
https://www.arangodb.com/docs/stable/drivers/js-reference-graph-edges.html
https://www.arangodb.com/docs/stable/drivers/js-reference-graph-vertex-collection.html
https://www.arangodb.com/docs/stable/drivers/js-reference-graph-edge-collection.html

there's a page called "edge collection" but it talks about how to CRUD edges. the "edges" page is actually the one about how to CRUD edge collections, and they BOTH say "edge collection" at the top. same problem for Vertices vs Vertex Collections ... they're split across multiple pages which just makes stuff harder to find. Can we just copy paste all these files into one file, like

Graphs
Graph CRUD
(One *complete* example of how to create a graph with vertex and edge collections)
(One *complete* example of how to CRUD vertex and an edge on that graph)
Vertex Collection CRUD
Vertex CRUD
Edge Collection CRUD
Edge CRUD

**Comment by bionicles** [comment]
The example for how to create a graph is like this:

```
const db = new Database();
const graph = db.graph('some-graph');
const info = await graph.create({
  edgeDefinitions: [{
    collection: 'edges',
    from: ['start-vertices'],
    to: ['end-vertices']
  }]
});
// graph now exists
```
doesn't include any vertex collections. Don't you need vertex collections to make a graph and edge collections / definitions?

**Comment by bionicles** [comment]
Also, when I'm checking out ArangoDB, I want to jump into the JS docs right away, but you have to find and click 4 different links to get from arangoDb home screen to the docs for JS driver:

1. click docs
2. click drivers (a list of drivers pops up)
3. click javascript (a useless splash screen pops up)
4. click reference

Just imagine it were easier to get into... 

1. click docs
2. click javascript reference

**Comment by bionicles** [comment]
And in the header of the docs page, there's this "drivers" button -- what if that were just split into JS, Java, PHP, Go, etc, so you could easily jump directly to each language's reference instead of digging through nested menus?

**Comment by bionicles** [comment]
the docs are good, it's just, to know what i'm doing as a developer i want fewer screens to navigate through because then it's exponentially easier to find what i need

**Comment by dothebart** [comment]
well, we decided against multi-screen long scrolling tree menus a wile back, thus its more clicks.
