### ISSUE TITLE
Starter: Active Failover, typo leading to agency failure

### ISSUE THREAD

**Issue by hamc17** [arangodb/docs#355]
In the section "deployment-active-failover-using-the-starter", under the subsection "Multiple Machines", the given command has a typo leading to failure of the agency.

The option `--agents.agency.supervision.grace-period` should be `--agents.agency.supervision-grace-period`.

**Comment by Simran-B** [comment]
Well spotted and thank you for letting us know! I corrected the command: https://github.com/arangodb/docs/commit/9d33d9c53b9ea833ab494a0002b3369275685ecd

It will take a few days before the change goes live.
