### ISSUE TITLE
typos/weird data in arangosearch examples

### ISSUE THREAD

**Issue by ex-nerd** [arangodb/docs#421]
See: https://github.com/arangodb/docs/blob/master/3.7/arangosearch-examples.md

Note that the example results being returned from `ExampleCollection1/128` contain a `c` property that doesn't exist.  I assume this is meant to be `i`, but the numeric values returned don't match any of the input data, either.

**Comment by Simran-B** [comment]
Thanks for letting us know about this mistake! It should be `"i": 4` and `"i": 5`.

PR: #423
