### ISSUE TITLE
The silent query parameter is not documented for some endpoints

### ISSUE THREAD

**Issue by DiscoPYF** [arangodb/docs#461]
In the Document HTTP API, there are a few endpoints that accept the `silent` query parameter but it's not documented.

- `PUT /_api/document/{collection}` (replaces multiple documents)
- `PATCH /_api/document/{collection}` (updates multiple documents)
- `DELETE /_api/document/{collection}` (removes multiple documents)

Found in ArangoDB docs stable 3.6.

https://www.arangodb.com/docs/stable/http/document-working-with-documents.html

I would expect the "Query Parameters" section of those endpoints to include the `silent` parameter, as it is done for other endpoints, e.g. `POST /_api/document/{collection}#multiple` (creates multiple documents).

> silent (optional): If set to true, an empty object will be returned as response. No meta-data will be returned for the created document. This option can be used to save some network traffic.

**Comment by joerg84** [comment]
Thanks, we are looking into this!
