### ISSUE TITLE
Logical OR || operator not displaying properly

### ISSUE THREAD

**Issue by cw00dw0rd** [arangodb/docs#52]
The logical OR doesn't show properly, unable to determine reason on quick glance of the md.
https://www.arangodb.com/docs/stable/aql/operators.html#logical-operators
![image](https://user-images.githubusercontent.com/7775349/58585571-163de000-8227-11e9-9007-840683e364b9.png)

**Comment by jsteemann** [comment]
Probably the `|` needs escaping in markdown? Will `\|` work?

**Comment by Simran-B** [comment]
Yes, it can be escaped with a backslash. The Markdown parser sees a table in pretty much an unescaped pipe character for some reason. My preferred solution regarding the AQL operators is to change the markup from italic to inline code.

It will take a bit of time to find a correct all `|`. I started a PR here: https://github.com/arangodb/docs/pull/54/files

**Comment by Simran-B** [comment]
Fixed: https://www.arangodb.com/docs/stable/aql/operators.html#logical-operators
