### ISSUE TITLE
Web UI: "ais-search-box--input" disappears

### ISSUE THREAD

**Issue by MKarat** [arangodb/docs#525]
The element "ais-search-box--input" completely disappears when window width is less than 918px. So there is no option for searching from small window (e.g. half desktop layout).  
width
URL: https://www.arangodb.com/docs/stable/
OS: Ubuntu 20.04
Browser: Google Chrome Version 84.0.4147.125 (Official Build) (64-bit)

Possible solution: search input can collapse to magnifier icon

![1](https://user-images.githubusercontent.com/52034247/90035051-0a262d00-dcca-11ea-9895-f3888d957e48.png)
![2](https://user-images.githubusercontent.com/52034247/90035054-0abec380-dcca-11ea-8872-c3a52db19f83.png)

**Comment by Simran-B** [comment]
It's still unclear if and what we will do about the design of the documentation and the search is supposed to be substituted (at least with Algolia doc search), but there's a lack of resources. The original idea was to replicate the header of the main website.
