### ISSUE TITLE
Broken link to ArangoSync

### ISSUE THREAD

**Issue by likemusic** [arangodb/docs#590]
https://github.com/arangodb/docs/blob/main/3.7/release-notes.md contains broken links to not exists ArangoSync page - https://github.com/arangodb/arangosync/blob/master/CHANGELOG.

I didn't find any repository like arangosync, therefore I can't make a PR with fix.

**Comment by Simran-B** [comment]
The link is correct, but it's a private repository. Need to check with the team what the best solution is here. We can potentially add a copy of the change log to the docs, so that it's publicly available.
