### ISSUE TITLE
Typo in the AQL

### ISSUE THREAD

**Issue by xsansha** [arangodb/docs#604]
I am new to AQL and checking out the search feature.
What I found is that the indentation of the RETURN doc is not maintained.

I am assuming this is a typo or it might not be.

Let me know if I am getting this thing wrong.

**Comment by dothebart** [comment]
Hi, 
Can you post a link to the place you mean?

**Comment by xsansha** [comment]
Hi @dothebart ,

https://www.arangodb.com/docs/stable/aql/operations-search.html

The following snippet is available in the **Syntax** section

```sql
FOR doc IN viewName
  SEARCH ANALYZER(doc.text == "quick" OR doc.text == "brown", "text_en")
RETURN doc
```

**Comment by dothebart** [comment]
prepared a fix, thanks for reporting.

**Comment by xsansha** [comment]
Actually, I was resembling the syntax with Python.

I think being pythonic might helped us here.

Thanks for the quick fix.

**Comment by Simran-B** [comment]
AQL does not have semantic whitespace, e.g.

```js
FOR doc IN coll
  UPDATE doc WITH { value: 1 } IN coll
FOR i IN 1..3
  RETURN i
```

will return three numbers per updated document and not once.

By our convention, each FOR body should be indented one more level for readability. I merged dothebart's PR which adjusts this for the SEARCH operation example. Thanks!
