### ISSUE TITLE
Wrong description: graph.edgeCollectionName.save(from, to, data, options)

### ISSUE THREAD

**Issue by joergwork** [arangodb/docs#625]
`https://www.arangodb.com/docs/stable/graphs-general-graphs-management.html#save-a-new-edge`

`graph.edgeCollectionName.save(from, to, data, options)`

does not work, it raises an "ArangoError: invalid document type"

For me, `graph.edgeCollectionName.save({ _from: "some/id", _to: "another/id"});` works.

It seems to me, that also the examples in `https://www.arangodb.com/docs/stable/data-modeling-documents-document-methods.html#edges` are wrong, as they still work with positional arguments.

**Comment by Simran-B** [comment]
Sorry, your issue slipped through the cracks between a lot of "internal" reminder issues. The docs appear to be wrong, indeed. Although, it's not fully clear whether the mentioned function signature is supposed to exist. The code that defines the relevant `bindEdgeCollections` in `js/common/modules/@arangodb/general-graph-common.js`  implements the following function signatures:

- `save(data)`
- `save(data, options)`
- `save(from, to, data)`

There is notably none with four parameters and only one that takes `options`. If `from` and `to` are passed separately, they are simply set as `_from` and `_to` on `data`. My conclusion is that `save(data[, options])` is preferable and should have the `_from` and `_to` attributes set. Docs will be adjusted by #880.
