### ISSUE TITLE
Typo in examples / join

### ISSUE THREAD

**Issue by adamkdean** [arangodb/docs#665]
> In the relational word you need a third table to model the many-to-many relation. In ArangoDB you have a choice depending on the information you are going to store and the type of questions you are going to ask.

> In the relational word

Should perhaps say "In the relational world".

https://www.arangodb.com/docs/stable/aql/examples-join.html

**Comment by Simran-B** [comment]
That's right, it is supposed to be "world". Thanks for reporting!

https://github.com/arangodb/docs/commit/cc22a8a76fb13769a62db78d3b7e33b0616277c0
