### ISSUE TITLE
Offline tarball for built docs

### ISSUE THREAD

**Issue by damooo** [arangodb/docs#700]
Thanks for great docs.
Is it possible to add pre-built docs as tarball to releases? It will be much straight forward to get docs offline rather than building ourself with all dependencies downlaoded.
Thanks again

**Comment by Simran-B** [comment]
Thank you @damooo!

The documentation is a product in its own right, even though it is largely coupled to minor ArangoDB versions. It is usually lagging a bit behind the code, but may as well get published independently, before or after a release. Being a moving target, I'm not sure how useful it would be to create tarballs when releases become generally available, as some content about the new version might still be missing.

Regarding dependencies, you can use our Docker image to build (and serve) the docs locally without having to install Jekyll etc.

**Comment by joerg84** [comment]
@damooo We are considering the request while upgrading the doc structure. Is it ok to close the issue for now?
