### ISSUE TITLE
Python async driver

### ISSUE THREAD

**Issue by mirrorrim** [arangodb/docs#725]
Hi!

I was looking for an asynchronous python driver and the only one was [aioarangodb](https://github.com/getflaps/aioarangodb) that hadn't been updated in over a year. Therefore, I decided to fork [python-arango](https://github.com/joowani/python-arango) as the most popular python library and make it asynchronous.

The current version (1.0.0) fully complient to python-arango 7.2.0.

Could you add this to the drivers list? https://github.com/mirrorrim/aioarango

**Comment by joerg84** [comment]
@mirrorrim Thanks, we will add it. Happy to chat about merging options with python-arango. Btw python-arango has graduated to the arangodb-community Github org.

**Comment by Simran-B** [comment]
Added to internal list, will be added to docs as part of #880.
