### ISSUE TITLE
Redirect loop documentation

### ISSUE THREAD

**Issue by ronaldpetty** [arangodb/docs#769]
This link is in an infinite loop it seems.

https://www.arangodb.com/docs/3.8/administration-leader-follower.html

Its not a 3yz, but some setting or cache (haven't debugged further).

**Comment by Simran-B** [comment]
Thanks, the redirect was actually broken in source. Fixed by https://github.com/arangodb/docs/commit/b16cb103e006fb60cf2e8da896d0e60d186129b0. Will be live soon.
