### ISSUE TITLE
ArangoSearch FuzzySearch misleading analyzer example.

### ISSUE THREAD

**Issue by grozail** [arangodb/docs#823]
I was experimenting with arangosearch functionality, particularly with NGRAM_MATCH.
Used this guide: https://www.arangodb.com/docs/3.8/arangosearch-fuzzy-search.html#searching-with-ngram_match
There is a misleading example of analyzer creation for trigram:

```js
//db._useDatabase("your_database"); // Analyzer will be created in current database
var analyzers = require("@arangodb/analyzers");
analyzers.save("trigram", "ngram", { min: 3, max: 3, preserveOriginal: false, streamType: "utf8" }, ["frequency", "norm"]);
```

Should be:

```js
//db._useDatabase("your_database"); // Analyzer will be created in current database
var analyzers = require("@arangodb/analyzers");
analyzers.save("trigram", "ngram", { min: 3, max: 3, preserveOriginal: false, streamType: "utf8" }, ["frequency", "norm", "position"]);
```

There are no direct instructions about the necessary "position" feature in order to make the `ngram` analyzer work in the official documentation or at least I have not found ones. https://www.arangodb.com/docs/3.8/arangosearch-fuzzy-search.html#searching-with-ngram_match

It would be much better if such nuance was covered.

But there are such instructions [here](https://colab.research.google.com/github/arangodb/interactive_tutorials/blob/master/notebooks/FuzzySearch.ipynb#scrollTo=a7RJtPcu8KnF) and this notebook was really helpful.

Thank you in advance for your attention!

**Comment by joerg84** [comment]
Thanks for raising this, it is currently addressed by https://github.com/arangodb/docs/pull/813

**Comment by joerg84** [comment]
As #813 is merged we close this one as well, please feel free to provide more feedback if needed.
