### ISSUE TITLE
[HTTP API] Named Indexes documentation missing

### ISSUE THREAD

**Issue by ifcologne** [arangodb/docs#87]
The named indexes are not mentioned in the HTTP API documentation. The only sentence I can find is this:

> Optionally, an index name may be specified as a string in the name attribute. Index names have the same restrictions as collection names. If no value is specified, one will be auto-generated.

The `name` attribute should be added to every index type as an optional parameter when creating an index.

**Comment by Simran-B** [comment]
https://github.com/arangodb/arangodb/pull/8370/files?file-filters%5B%5D=.md&show-viewed-files=false

No section about named indices in manual, however. See DOC-38
