### ISSUE TITLE
The unit for lockTimeout option is not specified in the HTTP documentation

### ISSUE THREAD

**Issue by DiscoPYF** [arangodb/docs#938]
Clients of the HTTP API for JS-transactions or Stream Transactions don't know what unit is used for option `lockTimeout`, as it is not documented. Is it milliseconds, seconds, minutes? It should be mentioned.

https://www.arangodb.com/docs/stable/http/transaction-js-transaction.html#execute-transaction

https://www.arangodb.com/docs/stable/http/transaction-stream-transaction.html#begin-a-transaction

> lockTimeout: an optional numeric value that can be used to set a timeout for waiting on collection locks. If not specified, a default value will be used. Setting lockTimeout to 0 will make ArangoDB not time out waiting for a lock.

The unit is only mentioned for what looks like a related ArangoDB Server option, but it is not clear if they refer to the same functionality: https://www.arangodb.com/docs/stable/programs-arangod-transaction.html

> transaction.streaming-lock-timeout
Lock timeout in seconds in case of parallel access to the same Stream Transaction.

Additionally, we don't have much information about what the default value is and how it is determined. What is the default value? Is it a fixed value used if the related Server option is not provided?

The article for RC7 of ArangoDB 3.5 mention that it is 10 minutes by default, still no unit: https://www.arangodb.com/2019/08/rc7-of-arangodb-3-5-streaming-transactions-api/

> lockTimeout: lets you specify the maximum time the transaction to be completed (default is 10 minutes)

Could you please update the relevant parts of the online doc to close the gaps mentioned above for `lockTimeout`?

It's worth noting that the quality of the documentation has got much better in recent releases, so thank you for all the improvements 👍

**Comment by Simran-B** [comment]
The unit is seconds according to one of our engineers. I will take care of the necessary documentation adjustments.
